### PR TITLE
Add support for Network Tomography

### PR DESCRIPTION
**Pull request by greenpau**
This commit adds support for Consul's network tomography. The
tomography is a collection of nodes' coordinates and RTT between the nodes.

See also: [Network Coordinates](https://www.consul.io/docs/internals/coordinates.html)

### CODE REVIEW

**Comment by greenpau** [comment]
@gmr , tests are passing. Is there a problem with the `coverage`?

```
The command "mkdir coverage" exited with 0.
3.60s$ aws s3 cp --recursive s3://com-gavinroy-travis/consulate/$TRAVIS_BUILD_NUMBER/ coverage
fatal error: Unable to locate credentials
The command "aws s3 cp --recursive s3://com-gavinroy-travis/consulate/$TRAVIS_BUILD_NUMBER/ coverage" exited with 1.
0.01s$ cd coverage
The command "cd coverage" exited with 0.
0.17s$ coverage combine
No data to combine
The command "coverage combine" exited with 1.
0.00s$ cd ..
The command "cd .." exited with 0.
0.01s$ mv coverage/.coverage .
mv: cannot stat ‘coverage/.coverage’: No such file or directory
```

**Comment by gmr** [comment]
Thanks!

**Comment by gmr** [comment]
I think the coverage issues are just PR vs main repo.

**Comment by greenpau** [comment]
@gmr , kudoz on `consulate` 👍 The structure and flow of the package is great!

**Comment by gmr** [comment]
Thanks!

**Pull request merged**
